"""add inclusion_requests workflow tables

Revision ID: 636d01f3cff0
Revises: 3dfa3c81c583
Create Date: 2026-07-24 13:16:06.907408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '636d01f3cff0'
down_revision: Union[str, Sequence[str], None] = '3dfa3c81c583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inclusion_requests',
    sa.Column('req_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('info_id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.Text(), nullable=True, comment='Название информационного источника, используемого для создания и обновления набора'),
    sa.Column('data_composition', sa.Text(), nullable=True, comment='Состав сведений, включаемых в набор, включая ограничительный гриф (при наличии)'),
    sa.Column('territory', sa.Text(), nullable=True, comment='Территория покрытия набора'),
    sa.Column('action_type', sa.Text(), nullable=False, comment='Первичное включение или обновление ранее включённого набора'),
    sa.Column('resource_url', sa.Text(), nullable=True, comment='Ссылка на ресурс, содержащий включаемый набор и метаданные о нём'),
    sa.Column('access_variant', sa.Text(), nullable=False, comment='Общий публичный или защищённый с регистрацией пользователя'),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('previous_request_id', sa.Integer(), nullable=True, comment='Ссылка на предыдущую заявку при повторной подаче после доработки'),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True, comment='Дата фактической публикации набора на Национальном геопортале'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.dataset_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['info_id'], ['info_types.info_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['previous_request_id'], ['inclusion_requests.req_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['status_id'], ['stages.stage_id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('req_id')
    )
    op.create_table('inclusion_request_history',
    sa.Column('history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('req_id', sa.Integer(), nullable=True),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responsible_id', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['req_id'], ['inclusion_requests.req_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsible_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.stage_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.add_column('stage_documents', sa.Column('inclusion_history_id', sa.Integer(), nullable=True))
    op.create_foreign_key('stage_documents_inclusion_history_id_fkey', 'stage_documents', 'inclusion_request_history', ['inclusion_history_id'], ['history_id'], ondelete='CASCADE')
    # ### end Alembic commands ###

    # Этапы воронки заявки о включении в НИПД (Постановление №32, п.7 Положения о НИПД)
    op.execute("""
        INSERT INTO stages (stage_name, stage_order, track_category, stage_type, stage_color, stage_code) VALUES
        ('Подана', 1, '5. Заявка на включение в НИПД', 'Веха', '#9c7509', 'INCL_SUBMITTED'),
        ('На рассмотрении', 2, '5. Заявка на включение в НИПД', 'Задача', '#9c9409', 'INCL_REVIEW'),
        ('Включена', 3, '5. Заявка на включение в НИПД', 'Веха', '#1d8207', 'INCL_APPROVED'),
        ('Отказано', 4, '5. Заявка на включение в НИПД', 'Веха', '#9c3309', 'INCL_REJECTED'),
        ('Спор в Госкомимущество', 5, '5. Заявка на включение в НИПД', 'Задача', '#4a0782', 'INCL_DISPUTE'),
        ('Публикация на геопортале', 6, '5. Заявка на включение в НИПД', 'Задача', '#075f82', 'INCL_PUBLISHING'),
        ('Закрыта', 7, '5. Заявка на включение в НИПД', 'Веха', '#09099c', 'INCL_CLOSED')
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DELETE FROM stages WHERE track_category = '5. Заявка на включение в НИПД'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('stage_documents_inclusion_history_id_fkey', 'stage_documents', type_='foreignkey')
    op.drop_column('stage_documents', 'inclusion_history_id')
    op.drop_table('inclusion_request_history')
    op.drop_table('inclusion_requests')
    # ### end Alembic commands ###
