"""add full_supplier_name to suppliers

Revision ID: e1abcafd5901
Revises: 3f7537fcc5d0
Create Date: 2026-07-14 10:27:00.209306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1abcafd5901'
down_revision: Union[str, Sequence[str], None] = '3f7537fcc5d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('full_supplier_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'full_supplier_name')
    # ### end Alembic commands ###
